markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
highlighter: rouge

permalink: blog/:year/:month/:day/:title.html
paginate: 7
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true
gems: [jekyll-paginate]

blog:
    name: Zhouqi
    description: Never Depend Never Find Very Silent Very Proud 
    title: 周七的博客
    url: zhouqi.com
    duoshuo: zhouqi
    tongji: zhouqi
    qiniu: # 七牛云地址
author:
    name: 周琪琪
    email: a123de7@163.com
    weibo: http://weibo.com/u/5336437516
    github: https://github.com/123de7
    logo: /res/img/psb.jpg
    douban:
        name: http://www.douban.com/people/103498505/
        key: 07e5af1c9cee1a1a17b10d55d6ca4e4e        
